#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
nm-applet &
$HOME/.config/polybar/launch.sh --shapes
# feh --bg-fill /usr/share/backgrounds/bspwm/wall.png
feh --bg-fill $HOME/Wallpapers/wall.jpg
flameshot &
picom &
/opt/clash-for-windows-bin/cfw &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I:TERM II:BROW III:DEV IV:LIFE V:OTHER


bspc config border_width         5
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


